# Generated by Django 5.2.12 on 2026-03-31 14:27

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_category_id_alter_like_id_alter_note_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, max_length=255, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='document.tag'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='document_no_created_2bc939_idx'),
        ),
    ]
