# Generated by Django 5.2.12 on 2026-04-01 15:08

import autoslug.fields
import document.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', slugify=document.models.unicode_slugify, unique=True),
        ),
    ]
